import type { TJobOffer } from "@/types/TJobOffer";

export const jobOffersMock: TJobOffer[] = [
  {
    id: "TQv2eNe0Egjjv6o91Xrh",
    title: "commercial executive (product & bundles)",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "6q8eAw",
    level: "mid-level",
    summary:
      "this role is key to growing our business and enhancing our product offerings.",
    description:
      "Source products such as chocolates, gifts, and perfumes. Negotiate with suppliers and maintain strong supplier relationships. Create attractive product bundles (e.g., flowers + gifts). Set pricing and ensure healthy profit margins. Analyze best-selling products and monitor customer trends. Plan seasonal campaigns. Enhance product presentation for maximum appeal. Coordinate closely with the sales and marketing teams.",
    qualifications:
      "2+ years of experience in product management, commercial, or retail roles. Strong negotiation and supplier management skills. Analytical mindset with ability to track trends and sales data. Good understanding of pricing, margins, and profit optimization. Excellent communication and teamwork skills. Fluency in English; additional languages are a plus.",
    skills:
      "Strategic planning and product development. Market research and trend analysis. Supplier negotiation and relationship management. Creativity in product bundling and promotions. Attention to detail and organizational skills.",
    salary: {
      currency: "QAR",
      min: undefined,
      max: undefined,
    },
    expirationDate: new Date("2026-05-30T21:00:00Z"),
    totalApplicantsCount: 12,
    createdAt: new Date("2026-04-01T09:25:27.820Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "0SrHUGG0y7HzdJOmtFj3",
    title: "sales director",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "nF68e9",
    level: "senior level",
    summary:
      "we are currently hiring for a leading client in the healthcare sector in qatar and are looking to connect with experienced professionals!",
    description:
      "The Sales Director will lead the commercial strategy and sales operations for a medical portfolio in Qatar.",
    qualifications:
      "Bachelor’s degree... Minimum 12–15 years experience... Strong knowledge of Qatar healthcare market...",
    skills:
      "Strategic planning, P&L ownership, contract negotiation, leadership, CRM tracking...",
    salary: {
      currency: "QAR",
      min: undefined,
      max: undefined,
    },
    expirationDate: new Date("2026-04-29T21:00:00Z"),
    totalApplicantsCount: 3,
    createdAt: new Date("2026-02-19T10:30:23.100Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "AaHayN9QxMQokKRD2DY3",
    title: "finance manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "vADVS9",
    level: "senior level",
    summary:
      "we are seeking an experienced finance manager to oversee financial operations for hospitals, clinics, or medical equipment businesses.",
    description:
      "We are seeking an experienced Finance Manager to oversee financial operations for hospitals, clinics, or medical equipment businesses.",
    qualifications:
      "CPA/ACCA preferred. 7–10 years finance experience. Healthcare background required.",
    skills:
      "ERP systems, budgeting, reporting, compliance, analytical skills...",
    salary: {
      currency: "QAR",
      min: undefined,
      max: undefined,
    },
    expirationDate: new Date("2026-04-29T21:00:00Z"),
    totalApplicantsCount: 116,
    createdAt: new Date("2026-02-26T12:26:33.740Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "ENBUOWJa15l3CZkEnToE",
    title: "florist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "HGh0Y9",
    level: "entry level to mid-level",
    summary:
      "we are looking for a skilled and efficient florist to maintain high-quality arrangements, especially during busy periods.",
    description:
      "Prepare bouquets and floral arrangements. Handle custom orders. Maintain quality standards. Manage storage. Reduce waste.",
    qualifications:
      "1–3 years florist experience. Strong design sense. Ability to work under pressure.",
    skills: "Creativity, attention to detail, time management, teamwork",
    salary: {
      currency: "QAR",
      min: undefined,
      max: undefined,
    },
    expirationDate: new Date("2026-04-29T21:00:00Z"),
    totalApplicantsCount: 0,
    createdAt: new Date("2025-06-30T12:27:00.844Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "GSRRQlJlpgpI4MpW7UuR",
    title: "clinical application specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "BXF0KH",
    level: "mid-level",
    summary:
      "we are currently hiring for a leading client in the healthcare sector in qatar and are looking to connect with experienced professionals",
    description:
      "The Clinical Application Specialist will provide installation support, training, and post-sales assistance.",
    qualifications:
      "Biomedical Engineering or related field. 3–6 years experience.",
    skills: "Training, troubleshooting, installation, communication",
    salary: {
      currency: "QAR",
      min: undefined,
      max: undefined,
    },
    expirationDate: new Date("2026-04-29T21:00:00Z"),
    totalApplicantsCount: 0,
    createdAt: new Date("2026-02-19T10:39:24.518484Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "H6jK8l9M0n1O2p3Q4r5S",
    title: "marketing manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "MKT023",
    level: "senior level",
    summary: "driving brand awareness and lead generation for our healthcare services.",
    description: "Develop and execute comprehensive marketing strategies, manage social media presence, and coordinate with sales teams for integrated campaigns.",
    qualifications: "Bachelor's degree in Marketing. 8+ years of experience. Experience in healthcare sector is a plus.",
    skills: "Digital marketing, brand management, SEO/SEM, content strategy",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-15T21:00:00Z"),
    totalApplicantsCount: 45,
    createdAt: new Date("2026-04-05T08:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "T7uV8w9X0y1Z2a3B4c5D",
    title: "operations coordinator",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "OPS045",
    level: "mid-level",
    summary: "streamlining daily operations and improving efficiency across departments.",
    description: "Oversee logistics, manage inventory, and optimize internal workflows to ensure smooth business operations.",
    qualifications: "Degree in Business Administration or related field. 4+ years of operations experience.",
    skills: "Process improvement, project management, logistics, team coordination",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-07-20T21:00:00Z"),
    totalApplicantsCount: 18,
    createdAt: new Date("2026-04-10T14:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "E6fG7h8I9j0K1l2M3n4O",
    title: "software engineer (frontend)",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "DEV089",
    level: "mid-level",
    summary: "building beautiful and responsive user interfaces for our digital platforms.",
    description: "Work closely with designers to implement web applications using React and Tailwind CSS. Ensure high performance and cross-browser compatibility.",
    qualifications: "3+ years of React experience. Strong proficiency in HTML, CSS, and JS.",
    skills: "React, TypeScript, CSS, Responsive Design, State Management",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-01T21:00:00Z"),
    totalApplicantsCount: 120,
    createdAt: new Date("2026-04-12T11:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "P5qR6s7T8u9V0w1X2y3Z",
    title: "human resources specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "HR011",
    level: "mid-level",
    summary: "managing recruitment, onboarding, and employee relations.",
    description: "Handle the full recruitment lifecycle, from job posting to contract signing. Assist in performance reviews and employee development programs.",
    qualifications: "Degree in HR Management. 5+ years of experience in HR.",
    skills: "Recruitment, Qatari labor law, conflict resolution, onboarding",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-05-15T21:00:00Z"),
    totalApplicantsCount: 65,
    createdAt: new Date("2026-04-02T09:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "A1b2C3d4E5f6G7h8I9j0",
    title: "data analyst",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "DATA22",
    level: "entry level",
    summary: "interpreting data and providing actionable insights for business growth.",
    description: "Collect, process, and analyze data from various sources. Create dashboards and reports to visualize key metrics.",
    qualifications: "Bachelor's in Statistics, Math, or Computer Science. Proficiency in Excel and SQL.",
    skills: "Data visualization, SQL, Python/R, analytical thinking",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-10T21:00:00Z"),
    totalApplicantsCount: 88,
    createdAt: new Date("2026-04-14T10:15:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "K0l9J8h7G6f5E4d3C2b1",
    title: "customer support lead",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "SUPP09",
    level: "senior level",
    summary: "ensuring exceptional customer experiences and managing support teams.",
    description: "Lead the customer support team, handle escalated issues, and implement feedback loops to improve service quality.",
    qualifications: "7+ years in customer service. Proven leadership experience.",
    skills: "Empathy, problem-solving, training, leadership",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-30T21:00:00Z"),
    totalApplicantsCount: 22,
    createdAt: new Date("2026-03-20T16:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "Z9y8X7w6V5u4T3s2R1q0",
    title: "biomedical technician",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "BIO67",
    level: "entry level to mid-level",
    summary: "maintaining and repairing medical equipment to ensure safety and reliability.",
    description: "Perform routine maintenance and emergency repairs on clinical devices. Maintain accurate service records and ensure compliance with safety standards.",
    qualifications: "Diploma or Degree in Biomedical Engineering. 2+ years of hands-on experience.",
    skills: "Troubleshooting, technical documentation, medical equipment maintenance",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-07-15T21:00:00Z"),
    totalApplicantsCount: 14,
    createdAt: new Date("2026-04-08T12:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "M1n2O3p4Q5r6S7t8U9v0",
    title: "administrative assistant",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "ADMIN15",
    level: "entry level",
    summary: "providing essential support for office operations and management.",
    description: "Manage schedules, prepare documents, and assist with general office tasks to ensure organizational efficiency.",
    qualifications: "High school diploma or above. Excellent organizational skills.",
    skills: "Typing, office software, communication, time management",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-05-20T21:00:00Z"),
    totalApplicantsCount: 200,
    createdAt: new Date("2026-04-15T09:45:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "B8c7D6e5F4g3H2i1J0k9",
    title: "procurement specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "PROC44",
    level: "mid-level",
    summary: "securing goods and services at the best value while maintaining quality standards.",
    description: "Manage purchase orders, evaluate suppliers, and negotiate contracts for a wide range of medical and office supplies.",
    qualifications: "Degree in Supply Chain or Finance. 4+ years of procurement experience.",
    skills: "Negotiation, supplier evaluation, cost analysis, ERP usage",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-10-01T21:00:00Z"),
    totalApplicantsCount: 32,
    createdAt: new Date("2026-04-01T15:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "S0t1U2v3W4x5Y6z7A8b9",
    title: "logistics manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "LOG55",
    level: "senior level",
    summary: "optimizing supply chain movements and warehouse efficiency.",
    description: "Oversee the movement of goods, coordinate with shipping partners, and manage warehouse teams to ensure timely delivery.",
    qualifications: "Experience in logistics management. Knowledge of Qatari customs and regulations.",
    skills: "Supply chain management, leadership, inventory control, route planning",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-30T21:00:00Z"),
    totalApplicantsCount: 25,
    createdAt: new Date("2026-03-25T11:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "O9n8M7l6K5j4I3h2G1f0",
    title: "business development executive",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "BD88",
    level: "mid-level",
    summary: "identifying new business opportunities and building lasting client relationships.",
    description: "Conduct market research, pitch services to potential clients, and collaborate with marketing to develop growth strategies.",
    qualifications: "Degree in Business or Marketing. 3+ years experience in B2B sales.",
    skills: "Lead generation, networking, presentation, relationship building",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-30T21:00:00Z"),
    totalApplicantsCount: 52,
    createdAt: new Date("2026-04-11T13:10:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "V0w1X2y3Z4a5B6c7D8e9",
    title: "visual merchandiser",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "VISUAL2",
    level: "mid-level",
    summary: "creating visually appealing displays to enhance customer shopping experiences.",
    description: "Design and implement store layouts and window displays. Coordinate with product teams for seasonal launches.",
    qualifications: "Background in design or retailing. 2+ years of visual merchandising experience.",
    skills: "Creativity, space planning, attention to detail, trend awareness",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-07-05T21:00:00Z"),
    totalApplicantsCount: 12,
    createdAt: new Date("2026-04-13T10:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "F9e8D7c6B5a4Z3y2X1w0",
    title: "quality assurance specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "QA99",
    level: "mid-level",
    summary: "ensuring all products and services meet strict quality standards.",
    description: "Perform audits, document quality metrics, and implement corrective actions to maintain high operational standards.",
    qualifications: "Experience in QA/QC processes. Healthcare industry knowledge preferred.",
    skills: "Detail-oriented, auditing, documentation, process improvement",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-11-15T21:00:00Z"),
    totalApplicantsCount: 19,
    createdAt: new Date("2026-03-28T09:15:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "L1m2N3o4P5q6R7s8T9u0",
    title: "receptionist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "RECEPT1",
    level: "entry level",
    summary: "representing the company as the first point of contact for visitors and callers.",
    description: "Manage front desk inquiries, coordinate meeting room bookings, and handle incoming and outgoing mail.",
    qualifications: "Experience in a hospitality or office role. Excellent verbal communication.",
    skills: "Professionalism, multitasking, phone etiquette, hospitality",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-10T21:00:00Z"),
    totalApplicantsCount: 156,
    createdAt: new Date("2026-04-14T14:40:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "Q2w3E4r5T6y7U8i9O0p1",
    title: "supply chain coordinator",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "SCM123",
    level: "mid-level",
    summary: "coordinating between suppliers and distribution channels.",
    description: "Monitor stock levels, track shipments, and ensure smooth information flow between procurement and logistics teams.",
    qualifications: "3+ years in supply chain or logistics role.",
    skills: "Data tracking, coordination, communication, ERP systems",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-12-01T21:00:00Z"),
    totalApplicantsCount: 21,
    createdAt: new Date("2026-04-06T15:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "X0c9V8b7N6m5A4s3D2f1",
    title: "graphic designer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "DSGN7",
    level: "mid-level",
    summary: "creating visually compelling graphics for digital and print media.",
    description: "Develop brand assets, social media posts, and marketing collateral. Ensure consistency in visual communication.",
    qualifications: "Portfolio of design work. Proficiency in Adobe Creative Suite.",
    skills: "Adobe Photoshop, Illustrator, layout design, creative thinking",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-15T21:00:00Z"),
    totalApplicantsCount: 42,
    createdAt: new Date("2026-04-09T11:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "G1h2J3k4L5m6N7o8P9q0",
    title: "social media specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "SOCIAL4",
    level: "entry level to mid-level",
    summary: "engaging audiences and managing online communities.",
    description: "Create content plans, manage social accounts, and interact with followers to build brand loyalty and awareness.",
    qualifications: "Experience in social media management. Strong content creation skills.",
    skills: "Communication, content curation, community management",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-25T21:00:00Z"),
    totalApplicantsCount: 78,
    createdAt: new Date("2026-04-12T09:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "K9j8H7g6F5d4S3a2Q1w0",
    title: "biomedical clinical lead",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "BIO_LEAD",
    level: "senior level",
    summary: "leading the clinical engineering team and overseeing major projects.",
    description: "Manage the biomedical department, ensure compliance with healthcare regulations, and supervise large-scale equipment installations.",
    qualifications: "Masters in Biomedical Engineering preferred. 10+ years experience.",
    skills: "Leadership, strategic planning, engineering management",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-04-30T21:00:00Z"),
    totalApplicantsCount: 5,
    createdAt: new Date("2026-03-15T08:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "M0n9B8v7C6x5Z4l3K2j1",
    title: "account executive",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "ACC01",
    level: "mid-level",
    summary: "managing key client accounts and driving satisfaction.",
    description: "Serve as the primary point of contact for clients, identify needs, and coordinate internally to deliver solutions that meet client goals.",
    qualifications: "3–5 years experience in account management or sales.",
    skills: "Client relationship management, problem-solving, communication",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-10-15T21:00:00Z"),
    totalApplicantsCount: 29,
    createdAt: new Date("2026-04-03T16:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "P1o2I3u4Y5t6R7e8W9q0",
    title: "inventory controller",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "INV567",
    level: "mid-level",
    summary: "ensuring accurate stock levels and minimizing inventory shrinkage.",
    description: "Track inventory movements, perform regular stock counts, and analyze discrepancies to improve warehouse management.",
    qualifications: "3+ years specialized in inventory management.",
    skills: "Numerical accuracy, inventory software, detail-oriented",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-01T21:00:00Z"),
    totalApplicantsCount: 16,
    createdAt: new Date("2026-04-07T14:10:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "Z1x2C3v4B5n6M7l8K9j0",
    title: "safety officer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "SAFE_01",
    level: "mid-level",
    summary: "ensuring a safe working environment and compliance with HSE standards.",
    description: "Conduct regular safety inspections, manage risk assessments, and lead safety training sessions for all staff members.",
    qualifications: "NEBOSH certification or equivalent. 5+ years in HSE roles.",
    skills: "Risk assessment, emergency response, safety auditing",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-15T21:00:00Z"),
    totalApplicantsCount: 22,
    createdAt: new Date("2026-04-05T10:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "A8s7D6f5G4h3J2k1L0m9",
    title: "it support technician",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "IT_SUPP",
    level: "entry level",
    summary: "providing technical assistance and maintaining company hardware and software.",
    description: "Troubleshoot hardware issues, install software updates, and support employees with technical queries to ensure uptime.",
    qualifications: "Degree in IT or Computer Science. Certification in A+ or Network+ preferred.",
    skills: "Troubleshooting, networking basics, software installation",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-07-30T21:00:00Z"),
    totalApplicantsCount: 95,
    createdAt: new Date("2026-04-10T09:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "S1o2P3i4U5y6T7r8E9w0",
    title: "legal counsel",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "LEGAL_02",
    level: "senior level",
    summary: "providing legal guidance and ensuring regulatory compliance.",
    description: "Review contracts, advise on corporate law matters, and represent the company in legal discussions with external partners.",
    qualifications: "Law degree and admission to practice. 10+ years of corporate law experience.",
    skills: "Contract negotiation, legal drafting, compliance, litigation management",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-12-15T21:00:00Z"),
    totalApplicantsCount: 12,
    createdAt: new Date("2026-03-20T11:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "D1f2G3h4J5k6L7m8A9s0",
    title: "content writer",
    type: "part time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "CONTENT_W",
    level: "mid-level",
    summary: "crafting engaging stories and informative content for our platforms.",
    description: "Write blog posts, newsletter content, and website copies that align with our brand voice and SEO strategy.",
    qualifications: "Portfolio of published work. Exceptional writing skills in English.",
    skills: "SEO writing, storytelling, copyediting, research",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-20T21:00:00Z"),
    totalApplicantsCount: 64,
    createdAt: new Date("2026-04-14T15:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "F1g2H3j4K5l6Z7x8C9v0",
    title: "warehouse supervisor",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "WARE_SUP",
    level: "mid-level",
    summary: "overseeing daily warehouse operations and staff management.",
    description: "Manage shipping and receiving schedules, supervise warehouse staff, and ensure all safety protocols are strictly followed.",
    qualifications: "5+ years in warehouse or logistics management.",
    skills: "Team leadership, inventory management, safety compliance",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-10T21:00:00Z"),
    totalApplicantsCount: 38,
    createdAt: new Date("2026-04-01T08:45:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "G1h2J3k4L5m6M7n8B9v0",
    title: "training specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "TRAIN_01",
    level: "mid-level",
    summary: "developing and delivering employee training programs.",
    description: "Identify training needs, create educational materials, and facilitate workshops to enhance employee skills and performance.",
    qualifications: "Experience in corporate training or education. Strong presentation skills.",
    skills: "Curriculum development, public speaking, coaching",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-11-01T21:00:00Z"),
    totalApplicantsCount: 27,
    createdAt: new Date("2026-03-25T14:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "H1j2K3l4M5n6B7v8C9x0",
    title: "ux/ui designer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "UXUI_02",
    level: "mid-level",
    summary: "designing intuitive and user-centered digital experiences.",
    description: "Create wireframes, prototypes, and high-fidelity designs for web and mobile applications. Conduct user research to inform design decisions.",
    qualifications: "Proven UX/UI design portfolio. Proficiency in Figma or Adobe XD.",
    skills: "User research, wireframing, prototyping, visual design",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-05-30T21:00:00Z"),
    totalApplicantsCount: 55,
    createdAt: new Date("2026-04-12T16:10:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "J1k2L3m4N5o6P7q8R9s0",
    title: "facilities manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "FAC_MAN",
    level: "senior level",
    summary: "maintaining company buildings and equipment to ensure operational excellence.",
    description: "Oversee maintenance projects, manage vendor relationships, and ensure all facility systems are functioning correctly and safely.",
    qualifications: "Degree in Engineering or Facility Management. 8+ years experience.",
    skills: "Vendor management, project planning, maintenance supervision",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-20T21:00:00Z"),
    totalApplicantsCount: 15,
    createdAt: new Date("2026-04-02T10:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "K1l2M3n4B5v6C7x8D9z0",
    title: "telemarketing executive",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "TELE_MKT",
    level: "entry level",
    summary: "reaching out to potential clients via phone to introduce our services.",
    description: "Conduct outbound calls, qualify leads, and schedule appointments for the sales team. Maintain a positive and professional attitude.",
    qualifications: "Excellent communication skills. Previous experience in sales or customer service.",
    skills: "Persuasion, active listening, resilience, basic CRM usage",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-15T21:00:00Z"),
    totalApplicantsCount: 112,
    createdAt: new Date("2026-04-13T11:45:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "L1m2N3o4P5q6S7t8U9v0_2",
    title: "executive secretary",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "EXEC_SEC",
    level: "mid-level",
    summary: "providing high-level administrative support to company executives.",
    description: "Manage complex calendars, coordinate travel arrangements, and handle confidential information with discretion and professionalism.",
    qualifications: "Significant experience in a secretarial or personal assistant role.",
    skills: "Time management, organization, professional writing, discretion",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-10-30T21:00:00Z"),
    totalApplicantsCount: 34,
    createdAt: new Date("2026-03-15T09:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "M1n2B3v4C5x6D7z8E9r0",
    title: "compliance officer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "COMP_OFF",
    level: "mid-level",
    summary: "ensuring the company adheres to all legal and regulatory requirements.",
    description: "Monitor internal policies, conduct compliance audits, and provide guidance on regulatory changes to mitigate operational risks.",
    qualifications: "Degree in Law, Finance, or Business. 4+ years in compliance roles.",
    skills: "Attention to detail, analytical thinking, regulatory knowledge",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-05T21:00:00Z"),
    totalApplicantsCount: 19,
    createdAt: new Date("2026-04-06T13:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "N1o2P3q4R5s6T7u8V9w0",
    title: "product owner",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "PROD_OWN",
    level: "senior level",
    summary: "defining the product vision and managing the product backlog.",
    description: "Collaborate with stakeholders to define requirements, prioritize features, and guide the development team to deliver high-value products.",
    qualifications: "Experienced as a Product Owner or Product Manager. Knowledge of Agile methodologies.",
    skills: "Stakeholder management, backlog grooming, communication, visioning",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-07-15T21:00:00Z"),
    totalApplicantsCount: 10,
    createdAt: new Date("2026-04-08T15:40:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "O1p2Q3r4S5t6U7v8W9x0",
    title: "office manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "OFF_MAN",
    level: "mid-level",
    summary: "ensuring the office runs efficiently and supportively.",
    description: "Oversee administrative tasks, manage office supplies, and coordinate office events to maintain a positive work environment.",
    qualifications: "Proven experience in office management or administrative leadership.",
    skills: "Leadership, organization, problem-solving, facilities coordination",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-05-25T21:00:00Z"),
    totalApplicantsCount: 42,
    createdAt: new Date("2026-04-04T10:15:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "P1q2R3s4T5u6V7w8X9y0",
    title: "payroll specialist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "PAY_01",
    level: "mid-level",
    summary: "managing payroll processes and ensuring accurate salary distributions.",
    description: "Process monthly payroll, manage employee benefits calculations, and ensure compliance with tax and labor regulations.",
    qualifications: "Experience in payroll administration. Proficiency in payroll software.",
    skills: "Mathematical accuracy, attention to detail, data entry, confidentiality",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-12-01T21:00:00Z"),
    totalApplicantsCount: 28,
    createdAt: new Date("2026-04-09T09:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "Q1r2S3t4U5v6W7x8Z9a0",
    title: "media relations officer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "MEDIA_R",
    level: "mid-level",
    summary: "building and maintaining relationships with media outlets.",
    description: "Draft press releases, coordinate interviews, and manage the company's public image through media engagement.",
    qualifications: "Degree in PR, Communications, or Journalism. 3+ years in media relations.",
    skills: "Press release writing, networking, crisis communication, public speaking",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-06-10T21:00:00Z"),
    totalApplicantsCount: 31,
    createdAt: new Date("2026-04-11T14:50:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "R1s2T3u4V5w6X7y8Y9z0",
    title: "it security engineer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "IT_SEC_03",
    level: "senior level",
    summary: "protecting company data and systems from cyber threats.",
    description: "Implement security protocols, monitor systems for breaches, and conduct vulnerability assessments to ensure data integrity.",
    qualifications: "Degree in Cybersecurity or CompSci. Strong knowledge of firewall and encryption technologies.",
    skills: "Cybersecurity, risk management, network security, incident response",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-10-15T21:00:00Z"),
    totalApplicantsCount: 8,
    createdAt: new Date("2026-03-28T16:30:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "S1t2U3v4W5x6Z7y8A9b0",
    title: "recruitment coordinator",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "REC_COORD",
    level: "entry level",
    summary: "supporting the recruitment team with scheduling and candidate management.",
    description: "Schedule interviews, maintain candidate databases, and assist with the onboarding process for new hires.",
    qualifications: "Excellent organizational and communication skills. Interest in HR.",
    skills: "Scheduling, data management, interpersonal communication",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-05-15T21:00:00Z"),
    totalApplicantsCount: 145,
    createdAt: new Date("2026-04-15T08:20:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "T1u2V3w4X5y6Y7z8B9c0",
    title: "branch manager",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "BRANCH_M",
    level: "senior level",
    summary: "overseeing operations and performance of a specific business branch.",
    description: "Lead the branch team, manage budgets, and ensure branch-specific goals are met while maintaining high service standards.",
    qualifications: "Proven experience in management, preferably in a retail or service branch environment.",
    skills: "Operational management, leadership, budgeting, customer service excellence",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-09-30T21:00:00Z"),
    totalApplicantsCount: 18,
    createdAt: new Date("2026-03-10T11:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "U1v2W3x4Z5y6A7b8C9d0",
    title: "digital strategist",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "DIGI_STRAT",
    level: "senior level",
    summary: "developing long-term digital growth plans for the organization.",
    description: "Analyze market trends, optimize digital presence, and collaborate with various departments to integrate digital initiatives.",
    qualifications: "Extensive experience in digital marketing or strategy. Analytical mindset.",
    skills: "Strategic thinking, market analysis, digital trends, project leadership",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-11-15T21:00:00Z"),
    totalApplicantsCount: 9,
    createdAt: new Date("2026-04-03T15:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },

  {
    id: "V1w2X3y4Y5z6A7b8D9e0",
    title: "maintenance engineer",
    type: "full time",
    location: "qatar",
    isArchived: false,
    isPublished: true,
    employerId: "EEzI452awpUHMgbe1B1P",
    jobCode: "MAINT_ENG",
    level: "mid-level",
    summary: "maintaining and optimizing mechanical and electrical systems.",
    description: "Perform preventative maintenance, troubleshoot system failures, and ensure all building services are running at peak efficiency.",
    qualifications: "Degree in Mechanical or Electrical Engineering. 4+ years of relevant experience.",
    skills: "Troubleshooting, technical repair, system optimization",
    salary: { currency: "QAR", min: undefined, max: undefined },
    expirationDate: new Date("2026-08-01T21:00:00Z"),
    totalApplicantsCount: 24,
    createdAt: new Date("2026-04-07T12:00:00Z"),
    createdBy: "admin@elevate-mate.com",
  },
];
